### ISSUE TITLE
[DevOps] Compose file

### ISSUE THREAD

**Issue by paveltobias** [paveltobias/pv217#2]
We should write a [docker-compose.yml](https://docs.docker.com/compose) file that automates:
- the build of all of our services into Docker images;
- the pull of all 3rd-party Docker images we use (e.g. for PostgreSQL, Kafka, ...);
- the run of all of the containers with correct environment variables etc.

**Comment by simkosvorad** [comment]
Added branch docker-compose with full working service by running docker-compose up --build.
