### ISSUE TITLE
[Implementation] Metrics gathering and visualization

### ISSUE THREAD

**Issue by paveltobias** [paveltobias/pv217#4]
- Utilize [MicroProfile Metrics](https://quarkus.io/guides/microprofile-metrics) to gather some custom metrics in at least one of the service. 
- Set up Grafana + Prometheus to visualize the gathered metrics.

**Comment by JakubDoczy** [comment]
Implemented metrics gathering for homework service. Added prometheus.yml (prometheus will run on localhost:9090) and grafana-dashboard.json to `homework-service/src/java/resources`.
