### ISSUE TITLE
[Implementation] Health checks

### ISSUE THREAD

**Issue by paveltobias** [paveltobias/pv217#5]
Set up some meaningful liveness/readiness [health checks](https://quarkus.io/guides/microprofile-health) in at least one of the services.

**Comment by JakubDoczy** [comment]
Implemented simple health checks. When running services on localhost, you can check liveness by `http :<port>/health/liveness` and readiness by `http :<port>/health/readiness`. Note that quarkus runs default checks for database connection and kafka channel and these default checks are much better than the ones that I've added.
